In [2]:
#ADVANCED PYTHON

In [4]:
#Creating numpy arrays

In [7]:
 overview:  numpy is a numerical computation libraries is used for all the numerical calculations and 
 also for the scientific computation it stands as a foundational library to all remaining library
 data types of numpy:numpy is having a data type called as ndarry
        overview of ndarry ===> num of dimensions array

In [8]:
understanding array is similar like list

In [ ]:
interview question:what is the difference between array and list if given choice which one you prefer
ans:array ---->becz of its internal implementation and working is very efficient in an array comparing to list

In [9]:
#How to install array

In [13]:
! pop install numpy

'pop' is not recognized as an internal or external command,
operable program or batch file.


In [16]:
import numpy as np

In [ ]:
1.creating an array from regular python list or tuple using an array function

In [19]:
array_one=np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [22]:
numbers=[2,3,4,5]
array_two=np.array(numbers)
array_two

array([2, 3, 4, 5])

In [ ]:
#how to confirm and validate datatype

In [23]:
type(array_two)

numpy.ndarray

In [ ]:
2.Numpy offers several functions to create arrays with initial place holder content 

In [ ]:
Req:create an array of zeroes with desired shape(x,y)
    x--->rows
    y--->column

In [25]:
array_of_zeroes = np.zeros((3,4))
array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#use datatype in order to specify the data type like int16,int32,int64

In [33]:
array_of_ones_int = np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [ ]:
#to create an eyedentity matrix we use np.eye()
identity matrix= [1 0 0]
                 [0 1 0]
                 [0 0 1]

In [35]:
array_eye=np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
3.To create sequence of num ,numpy provides a function analogous to range that return arrays instead of lists
syntax:
    arange(start,step,dtype)

In [38]:
array_of_evens=np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
Note:Last value is always excusive